Repository meshery/meshery-cilium, pull requests merged in 2022-03, with the labels that each got.

#25 v0.5.x compatible Adapter registration
  Makefile
  go.mod
  go.sum
Labels: pr/dependencies

#31 Refactored Cilium Operations
  cilium/cilium.go
  cilium/operations.go
  internal/config/config.go
  internal/config/operations.go
Labels: area/lifecycle

#32 [Cl] Schedule Static Component Generation Workflow
  .github/workflows/component-generator.yml
  build/config.go
  cilium/oam/register.go
  main.go
  templates/oam/workloads/v1.12.0-rc0/ciliumclusterwidenetworkpolicy.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumclusterwidenetworkpolicy.meshery.layer5.io_definition.json
  templates/oam/workloads/v1.12.0-rc0/ciliumendpoint.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumendpoint.meshery.layer5.io_definition.json
  templates/oam/workloads/v1.12.0-rc0/ciliumexternalworkload.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumexternalworkload.meshery.layer5.io_definition.json
  templates/oam/workloads/v1.12.0-rc0/ciliumidentity.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumidentity.meshery.layer5.io_definition.json
  templates/oam/workloads/v1.12.0-rc0/ciliumlocalredirectpolicy.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumlocalredirectpolicy.meshery.layer5.io_definition.json
  templates/oam/workloads/v1.12.0-rc0/ciliumnetworkpolicy.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumnetworkpolicy.meshery.layer5.io_definition.json
  templates/oam/workloads/v1.12.0-rc0/ciliumnode.meshery.layer5.io.meshery.layer5io.schema.json
  templates/oam/workloads/v1.12.0-rc0/ciliumnode.meshery.layer5.io_definition.json
Labels: area/lifecycle

#34 Added MeshOps v1 Support
  Makefile
  cilium/error.go
  go.mod
  go.sum
  helpers/errorutil_analyze_errors.json
  helpers/errorutil_analyze_summary.json
  helpers/errorutil_errors_export.json
  internal/config/config.go
Labels: service-mesh/cilium
